development:
  adapter: postgresql
  encoding: unicode
  database: projet_final_development
  pool: 5
  username: postgres
  password: *****
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: projet_final_test
  pool: 5
  username: postgres
  password: *****
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: projet_final_production
  pool: 5
  username: postgres
  password: *****
  host: localhost
  port: 5432

cucumber:
  <<: *test

